- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    enabled: true
    state: reloaded

- name: Update aliases
  ansible.builtin.command: postalias /etc/aliases

- name: Update virtual aliases
  ansible.builtin.command: postmap /etc/postfix/virtual
